"""
Main Google Drive service class.
Integrates authentication and file operations for workflow usage.
"""

from pathlib import Path
from typing import Any, Dict, List, Optional

from loguru import logger

from core.services.google_drive.drive_auth import GoogleDriveAuth
from core.services.google_drive.drive_operations import GoogleDriveOperations


class GoogleDriveService:
    """
    Main Google Drive service for workflow integration.

    Provides high-level methods for file operations integrated with
    the ArcaAutoVep workflow system.
    """

    def __init__(
        self,
        credentials_path: str,
        token_path: str,
        scopes: Optional[List[str]] = None,
    ):
        """
        Initialize Google Drive service.

        Args:
            credentials_path: Path to Google OAuth2 credentials JSON
            token_path: Path to store/retrieve user tokens
            scopes: List of OAuth2 scopes (optional)
        """
        self.auth = GoogleDriveAuth(credentials_path, token_path, scopes)
        self.operations: Optional[GoogleDriveOperations] = None
        self._initialize_operations()

    def _initialize_operations(self) -> bool:
        """
        Initialize Google Drive operations with valid credentials.

        Returns:
            True if initialization successful, False otherwise
        """
        try:
            credentials = self.auth.get_credentials()
            if credentials:
                self.operations = GoogleDriveOperations(credentials)
                logger.info("Google Drive service initialized successfully")
                return True
            else:
                logger.error("Failed to obtain Google Drive credentials")
                return False
        except Exception as e:
            logger.error(f"Failed to initialize Google Drive operations: {e}")
            return False

    def is_available(self) -> bool:
        """
        Check if Google Drive service is available and authenticated.

        Returns:
            True if service is ready for use
        """
        return self.operations is not None and self.auth.is_authenticated()

    def upload_workflow_file(
        self,
        file_path: str,
        workflow_type: str,
        exchange_id: str,
        file_type: str = "pdf",
        custom_name: Optional[str] = None,
    ) -> Optional[str]:
        """
        Upload a workflow-generated file to Google Drive.

        Args:
            file_path: Local path to file to upload
            workflow_type: Type of workflow (ccma, ddjj)
            exchange_id: Workflow exchange ID
            file_type: Type of file (pdf, vep, qr)
            custom_name: Custom name for the file (optional)

        Returns:
            Google Drive file ID if successful, None otherwise
        """
        if not self.is_available():
            logger.error("Google Drive service not available")
            return None

        try:
            # Create organized folder structure
            folder_id = self._ensure_workflow_folder(workflow_type, exchange_id)

            # Generate descriptive filename if not provided
            if not custom_name:
                file_path_obj = Path(file_path)
                custom_name = (
                    f"{workflow_type}_{exchange_id}_{file_type}{file_path_obj.suffix}"
                )

            # Add workflow metadata
            metadata = {
                "description": f"Generated by {workflow_type} workflow",
                "properties": {
                    "workflow_type": workflow_type,
                    "exchange_id": exchange_id,
                    "file_type": file_type,
                    "generated_by": "ArcaAutoVep_api",
                },
            }

            # Upload file
            file_id = self.operations.upload_file(
                file_path=file_path,
                folder_id=folder_id,
                file_name=custom_name,
                metadata=metadata,
            )

            if file_id:
                logger.info(
                    f"Workflow file uploaded to Drive: {custom_name} "
                    f"(Exchange: {exchange_id}, File ID: {file_id})"
                )

            return file_id

        except Exception as e:
            logger.error(f"Failed to upload workflow file: {e}")
            return None

    def upload_file_content(
        self,
        content: bytes,
        file_name: str,
        mime_type: str,
        workflow_type: Optional[str] = None,
        exchange_id: Optional[str] = None,
    ) -> Optional[str]:
        """
        Upload file content directly to Google Drive.

        Args:
            content: File content as bytes
            file_name: Name for the uploaded file
            mime_type: MIME type of the file
            workflow_type: Type of workflow (optional)
            exchange_id: Workflow exchange ID (optional)

        Returns:
            Google Drive file ID if successful, None otherwise
        """
        if not self.is_available():
            logger.error("Google Drive service not available")
            return None

        try:
            folder_id = None
            metadata = {}

            # Add workflow organization if provided
            if workflow_type and exchange_id:
                folder_id = self._ensure_workflow_folder(workflow_type, exchange_id)
                metadata = {
                    "description": f"Generated by {workflow_type} workflow",
                    "properties": {
                        "workflow_type": workflow_type,
                        "exchange_id": exchange_id,
                        "generated_by": "ArcaAutoVep_api",
                    },
                }

            return self.operations.upload_file_content(
                content=content,
                file_name=file_name,
                mime_type=mime_type,
                folder_id=folder_id,
                metadata=metadata,
            )

        except Exception as e:
            logger.error(f"Failed to upload file content: {e}")
            return None

    def download_workflow_file(self, file_id: str, download_path: str) -> bool:
        """
        Download a file from Google Drive.

        Args:
            file_id: Google Drive file ID
            download_path: Local path to save the file

        Returns:
            True if download successful, False otherwise
        """
        if not self.is_available():
            logger.error("Google Drive service not available")
            return False

        return self.operations.download_file(file_id, download_path)

    def search_workflow_files(
        self,
        workflow_type: Optional[str] = None,
        exchange_id: Optional[str] = None,
        file_type: Optional[str] = None,
        max_results: int = 10,
    ) -> List[Dict[str, Any]]:
        """
        Search for workflow-generated files in Google Drive.

        Args:
            workflow_type: Filter by workflow type (optional)
            exchange_id: Filter by exchange ID (optional)
            file_type: Filter by file type (optional)
            max_results: Maximum number of results

        Returns:
            List of file metadata dictionaries
        """
        if not self.is_available():
            logger.error("Google Drive service not available")
            return []

        # Build search query
        query_parts = [
            "properties has { key='generated_by' and value='ArcaAutoVep_api' }"
        ]

        if workflow_type:
            query_parts.append(
                f"properties has {{ key='workflow_type' and value='{workflow_type}' }}"
            )

        if exchange_id:
            query_parts.append(
                f"properties has {{ key='exchange_id' and value='{exchange_id}' }}"
            )

        if file_type:
            query_parts.append(
                f"properties has {{ key='file_type' and value='{file_type}' }}"
            )

        query = " and ".join(query_parts)

        return self.operations.search_files(query, max_results)

    def delete_workflow_file(self, file_id: str) -> bool:
        """
        Delete a workflow file from Google Drive.

        Args:
            file_id: Google Drive file ID to delete

        Returns:
            True if deletion successful, False otherwise
        """
        if not self.is_available():
            logger.error("Google Drive service not available")
            return False

        return self.operations.delete_file(file_id)

    def _ensure_workflow_folder(
        self, workflow_type: str, exchange_id: str
    ) -> Optional[str]:
        """
        Ensure workflow folder structure exists and return folder ID.

        Args:
            workflow_type: Type of workflow (ccma, ddjj)
            exchange_id: Workflow exchange ID

        Returns:
            Folder ID for the workflow
        """
        try:
            # Create/get root ArcaAutoVep folder
            root_folder_id = self._get_or_create_folder("ArcaAutoVep")

            # Create/get workflow type folder
            workflow_folder_id = self._get_or_create_folder(
                workflow_type.upper(), root_folder_id
            )

            # Create/get exchange ID folder
            exchange_folder_id = self._get_or_create_folder(
                exchange_id, workflow_folder_id
            )

            return exchange_folder_id

        except Exception as e:
            logger.error(f"Failed to ensure workflow folder structure: {e}")
            return None

    def _get_or_create_folder(
        self, folder_name: str, parent_id: Optional[str] = None
    ) -> Optional[str]:
        """
        Get existing folder or create new one.

        Args:
            folder_name: Name of the folder
            parent_id: Parent folder ID (optional)

        Returns:
            Folder ID
        """
        # Search for existing folder
        query = (
            f"name='{folder_name}' and mimeType='application/vnd.google-apps.folder'"
        )
        if parent_id:
            query += f" and '{parent_id}' in parents"

        existing_folders = self.operations.search_files(query, max_results=1)

        if existing_folders:
            return existing_folders[0]["id"]
        else:
            # Create new folder
            return self.operations.create_folder(folder_name, parent_id)

    def get_file_share_link(self, file_id: str) -> Optional[str]:
        """
        Get a shareable link for a file.

        Args:
            file_id: Google Drive file ID

        Returns:
            Shareable link or None if failed
        """
        if not self.is_available():
            logger.error("Google Drive service not available")
            return None

        try:
            # Make file accessible via link
            permission = {"type": "anyone", "role": "reader"}

            self.operations.service.permissions().create(
                fileId=file_id, body=permission
            ).execute()

            # Return shareable link
            return f"https://drive.google.com/file/d/{file_id}/view"

        except Exception as e:
            logger.error(f"Failed to create share link: {e}")
            return None

    def cleanup_old_files(self, days_old: int = 30) -> int:
        """
        Clean up workflow files older than specified days.

        Args:
            days_old: Age threshold in days

        Returns:
            Number of files deleted
        """
        if not self.is_available():
            logger.error("Google Drive service not available")
            return 0

        try:
            from datetime import datetime, timedelta

            # Calculate cutoff date
            cutoff_date = datetime.now() - timedelta(days=days_old)
            cutoff_str = cutoff_date.isoformat()

            # Search for old workflow files
            query = (
                f"properties has {{ key='generated_by' and value='ArcaAutoVep_api' }} "
                f"and modifiedTime < '{cutoff_str}'"
            )

            old_files = self.operations.search_files(query, max_results=100)

            deleted_count = 0
            for file in old_files:
                if self.operations.delete_file(file["id"]):
                    deleted_count += 1

            logger.info(f"Cleaned up {deleted_count} old workflow files")
            return deleted_count

        except Exception as e:
            logger.error(f"Failed to cleanup old files: {e}")
            return 0
